-- Setup incremental para Plan de trabajo
-- Ejecutar en el schema de la aplicación.
-- Si una sentencia falla por columna existente/no existente, revísala según tu estado actual.

ALTER TABLE "ACTIVIDADES" ADD ("FRIENDLY_NAME" NVARCHAR(1000));
UPDATE "ACTIVIDADES"
SET "FRIENDLY_NAME" = COALESCE("FRIENDLY_NAME", "PLAN_TRABAJO")
WHERE COALESCE("PLAN_TRABAJO", '') <> '';

ALTER TABLE "ACTIVIDADES" DROP ("PLAN_TRABAJO");
ALTER TABLE "ACTIVIDADES" DROP ("NOMBRE_TECNICO");

ALTER TABLE "ACTIVIDADES" ADD ("DIAS_ACORDADOS" SMALLINT);
ALTER TABLE "ACTIVIDADES" ADD ("FECHA_FIN_EST" DATE);
ALTER TABLE "ACTIVIDADES" ADD ("TIPO" NVARCHAR(30));

CREATE OR REPLACE VIEW "VW_plan_de_trabajo" AS
SELECT
    A."ID",
    A."NOMBRE_ACTIVIDAD",
    A."FRIENDLY_NAME",
    A."ID_PROYECTO",
    P."NOMBRE_PROYECTO",
    A."ID_ESTATUS",
    E."DESCRIPCION" AS "ESTATUS",
    E."COLOR_HEX" AS "ESTATUS_COLOR",
    A."FECHA_INICIO",
    A."FECHA_FIN_EST",
    A."FECHA_FIN_REAL",
    A."DIAS_ACORDADOS",
    A."AVANCE_PCT",
    A."PRIORIDAD",
    A."CREADO_EN",
    CASE
        WHEN A."DIAS_ACORDADOS" IS NOT NULL
             AND A."FECHA_INICIO" IS NOT NULL
             AND DAYS_BETWEEN(A."FECHA_INICIO", CURRENT_DATE) > A."DIAS_ACORDADOS"
             AND UPPER(E."DESCRIPCION") NOT IN ('COMPLETADO', 'CANCELADO', 'ESPERANDO APROBACIÓN')
        THEN 1
        ELSE 0
    END AS "EN_RETRASO",
    COALESCE((
        SELECT STRING_AGG(U2."NOMBRE_COMPLETO", ', ')
        FROM "ACTIVIDAD_RESPONSABLES" AR
        JOIN "USUARIOS" U2 ON AR."ID_USUARIO" = U2."ID"
        WHERE AR."ID_ACTIVIDAD" = A."ID"
    ), 'Sin asignar') AS "RESPONSABLES"
FROM "ACTIVIDADES" A
JOIN "PROYECTOS" P ON A."ID_PROYECTO" = P."ID"
JOIN "CAT_ESTATUS_ACTIVIDAD" E ON A."ID_ESTATUS" = E."ID"
WHERE A."ID_ACTIVIDAD_PADRE" IS NULL
    AND UPPER(COALESCE(A."NOMBRE_ACTIVIDAD", '')) NOT LIKE '⚡ %'
WITH READ ONLY;
