-- A317FA664ABA425DB50CA4CF071C7AFC.USUARIOS definition

CREATE COLUMN TABLE "A317FA664ABA425DB50CA4CF071C7AFC"."USUARIOS" ("ID" NVARCHAR(36) NOT NULL ,
"NOMBRE_COMPLETO" NVARCHAR(100) NOT NULL ,
"EMAIL" NVARCHAR(150),
"PUESTO" NVARCHAR(100),
"ACTIVO" TINYINT DEFAULT 1 NOT NULL ,
"FECHA_ALTA" DATE NOT NULL ,
"FECHA_BAJA" DATE,
"MOTIVO_BAJA" NVARCHAR(255),
"CREADO_EN" LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL ,
"ACTUALIZADO_EN" LONGDATE,
"CREADO_POR" NVARCHAR(36),
"ACTUALIZADO_POR" NVARCHAR(36),
PRIMARY KEY ("ID")) UNLOAD PRIORITY 5 AUTO MERGE;



-- A317FA664ABA425DB50CA4CF071C7AFC.REGISTRO_ACTIVIDADES definition

CREATE COLUMN TABLE "A317FA664ABA425DB50CA4CF071C7AFC"."REGISTRO_ACTIVIDADES" ("ID" NVARCHAR(36) NOT NULL ,
"FECHA" DATE NOT NULL ,
"ID_USUARIO" NVARCHAR(36) NOT NULL ,
"ID_PROYECTO" NVARCHAR(36) NOT NULL ,
"ID_DETALLE" NVARCHAR(36),
"ID_TIPO_ACT" NVARCHAR(36),
"ACCION" NVARCHAR(255),
"HORAS" DECIMAL(4, 2) NOT NULL ,
"DETALLES" NVARCHAR(1000),
"CREADO_EN" LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL ,
"ACTUALIZADO_EN" LONGDATE,
"ID_ACTIVIDAD" NVARCHAR(36),
PRIMARY KEY ("ID")) UNLOAD PRIORITY 5 AUTO MERGE ;

ALTER TABLE "A317FA664ABA425DB50CA4CF071C7AFC"."REGISTRO_ACTIVIDADES" ADD FOREIGN KEY ("ID_USUARIO") REFERENCES "A317FA664ABA425DB50CA4CF071C7AFC"."USUARIOS" ("ID") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;

ALTER TABLE "A317FA664ABA425DB50CA4CF071C7AFC"."REGISTRO_ACTIVIDADES" ADD FOREIGN KEY ("ID_PROYECTO") REFERENCES "A317FA664ABA425DB50CA4CF071C7AFC"."PROYECTOS" ("ID") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;

ALTER TABLE "A317FA664ABA425DB50CA4CF071C7AFC"."REGISTRO_ACTIVIDADES" ADD FOREIGN KEY ("ID_DETALLE") REFERENCES "A317FA664ABA425DB50CA4CF071C7AFC"."DETALLE_ACTIVIDAD" ("ID") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;

ALTER TABLE "A317FA664ABA425DB50CA4CF071C7AFC"."REGISTRO_ACTIVIDADES" ADD FOREIGN KEY ("ID_TIPO_ACT") REFERENCES "A317FA664ABA425DB50CA4CF071C7AFC"."CAT_TIPO_ACTIVIDAD" ("ID") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;

ALTER TABLE "A317FA664ABA425DB50CA4CF071C7AFC"."REGISTRO_ACTIVIDADES" ADD CONSTRAINT "FK_REG_ACTIVIDAD" FOREIGN KEY ("ID_ACTIVIDAD") REFERENCES "A317FA664ABA425DB50CA4CF071C7AFC"."ACTIVIDADES" ("ID") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;



-- A317FA664ABA425DB50CA4CF071C7AFC.PROYECTOS definition

CREATE COLUMN TABLE "A317FA664ABA425DB50CA4CF071C7AFC"."PROYECTOS" ("ID" NVARCHAR(36) NOT NULL ,
"NOMBRE_PROYECTO" NVARCHAR(100) NOT NULL ,
"DESCRIPCION" NVARCHAR(500),
"CLIENTE" NVARCHAR(100),
"ACTIVO" TINYINT DEFAULT 1 NOT NULL ,
"FECHA_INICIO" DATE,
"FECHA_FIN_EST" DATE,
"FECHA_FIN_REAL" DATE,
"CREADO_EN" LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL ,
"ACTUALIZADO_EN" LONGDATE,
PRIMARY KEY ("ID")) UNLOAD PRIORITY 5 AUTO MERGE;



-- A317FA664ABA425DB50CA4CF071C7AFC.EVIDENCIA_ACTIVIDAD definition

CREATE COLUMN TABLE "A317FA664ABA425DB50CA4CF071C7AFC"."EVIDENCIA_ACTIVIDAD" ("ID" NVARCHAR(36) NOT NULL ,
"ID_ACTIVIDAD" NVARCHAR(36) NOT NULL ,
"ID_TIPO" NVARCHAR(36) NOT NULL ,
"TITULO" NVARCHAR(255),
"CONTENIDO_TEXTO" NCLOB MEMORY THRESHOLD 1000,
"NOMBRE_ARCHIVO" NVARCHAR(255),
"URL_ARCHIVO" NVARCHAR(1000),
"MIME_TYPE" NVARCHAR(100),
"TAMANO_BYTES" BIGINT,
"SUBIDO_POR" NVARCHAR(36),
"CREADO_EN" LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL ,
PRIMARY KEY ("ID")) UNLOAD PRIORITY 5 AUTO MERGE ;

ALTER TABLE "A317FA664ABA425DB50CA4CF071C7AFC"."EVIDENCIA_ACTIVIDAD" ADD FOREIGN KEY ("ID_ACTIVIDAD") REFERENCES "A317FA664ABA425DB50CA4CF071C7AFC"."ACTIVIDADES" ("ID") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;

ALTER TABLE "A317FA664ABA425DB50CA4CF071C7AFC"."EVIDENCIA_ACTIVIDAD" ADD FOREIGN KEY ("ID_TIPO") REFERENCES "A317FA664ABA425DB50CA4CF071C7AFC"."CAT_TIPO_EVIDENCIA" ("ID") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;

ALTER TABLE "A317FA664ABA425DB50CA4CF071C7AFC"."EVIDENCIA_ACTIVIDAD" ADD FOREIGN KEY ("SUBIDO_POR") REFERENCES "A317FA664ABA425DB50CA4CF071C7AFC"."USUARIOS" ("ID") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;




-- A317FA664ABA425DB50CA4CF071C7AFC.DETALLE_ACTIVIDAD definition

CREATE COLUMN TABLE "A317FA664ABA425DB50CA4CF071C7AFC"."DETALLE_ACTIVIDAD" ("ID" NVARCHAR(36) NOT NULL ,
"ID_ACTIVIDAD" NVARCHAR(36) NOT NULL ,
"ID_TIPO" NVARCHAR(36) NOT NULL ,
"DESCRIPCION" NVARCHAR(1000) NOT NULL ,
"RESPONSABLE" NVARCHAR(36),
"FECHA_REGISTRO" DATE NOT NULL ,
"HORAS_ESTIMADAS" DECIMAL(5, 2),
"HORAS_REALES" DECIMAL(5, 2),
"COMPLETADO" TINYINT DEFAULT 0,
"NOTAS" NVARCHAR(500),
"CREADO_EN" LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL ,
"CREADO_POR" NVARCHAR(36),
PRIMARY KEY ("ID")) UNLOAD PRIORITY 5 AUTO MERGE ;

ALTER TABLE "A317FA664ABA425DB50CA4CF071C7AFC"."DETALLE_ACTIVIDAD" ADD FOREIGN KEY ("ID_ACTIVIDAD") REFERENCES "A317FA664ABA425DB50CA4CF071C7AFC"."ACTIVIDADES" ("ID") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;

ALTER TABLE "A317FA664ABA425DB50CA4CF071C7AFC"."DETALLE_ACTIVIDAD" ADD FOREIGN KEY ("ID_TIPO") REFERENCES "A317FA664ABA425DB50CA4CF071C7AFC"."CAT_TIPO_ACTIVIDAD" ("ID") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;

ALTER TABLE "A317FA664ABA425DB50CA4CF071C7AFC"."DETALLE_ACTIVIDAD" ADD FOREIGN KEY ("RESPONSABLE") REFERENCES "A317FA664ABA425DB50CA4CF071C7AFC"."USUARIOS" ("ID") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;



-- A317FA664ABA425DB50CA4CF071C7AFC.CAT_TIPO_EVIDENCIA definition

CREATE COLUMN TABLE "A317FA664ABA425DB50CA4CF071C7AFC"."CAT_TIPO_EVIDENCIA" ("ID" NVARCHAR(36) NOT NULL ,
"CLAVE" NVARCHAR(30) NOT NULL ,
"DESCRIPCION" NVARCHAR(100) NOT NULL ,
"ACTIVO" TINYINT DEFAULT 1 NOT NULL ,
PRIMARY KEY ("ID")) UNLOAD PRIORITY 5 AUTO MERGE; 




-- A317FA664ABA425DB50CA4CF071C7AFC.CAT_TIPO_ACTIVIDAD definition

CREATE COLUMN TABLE "A317FA664ABA425DB50CA4CF071C7AFC"."CAT_TIPO_ACTIVIDAD" ("ID" NVARCHAR(36) NOT NULL ,
"CLAVE" NVARCHAR(30) NOT NULL ,
"DESCRIPCION" NVARCHAR(100) NOT NULL ,
"ORDEN" TINYINT DEFAULT 0,
"ACTIVO" TINYINT DEFAULT 1 NOT NULL ,
PRIMARY KEY ("ID")) UNLOAD PRIORITY 5 AUTO MERGE;



-- A317FA664ABA425DB50CA4CF071C7AFC.CAT_RECURSOS definition

CREATE COLUMN TABLE "A317FA664ABA425DB50CA4CF071C7AFC"."CAT_RECURSOS" ("ID" NVARCHAR(36) DEFAULT SYSUUID,
"NOMBRE" NVARCHAR(100) NOT NULL ,
"DESCRIPCION" NVARCHAR(255),
"ICONO" NVARCHAR(50),
"ACTIVO" TINYINT DEFAULT 1,
"CREADO_EN" LONGDATE DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY ("ID")) UNLOAD PRIORITY 5 AUTO MERGE;


-- A317FA664ABA425DB50CA4CF071C7AFC.CAT_ESTATUS_ACTIVIDAD definition

CREATE COLUMN TABLE "A317FA664ABA425DB50CA4CF071C7AFC"."CAT_ESTATUS_ACTIVIDAD" ("ID" NVARCHAR(36) NOT NULL ,
"CLAVE" NVARCHAR(30) NOT NULL ,
"DESCRIPCION" NVARCHAR(100) NOT NULL ,
"COLOR_HEX" NVARCHAR(7),
"ORDEN" TINYINT DEFAULT 0,
"ACTIVO" TINYINT DEFAULT 1 NOT NULL ,
PRIMARY KEY ("ID")) UNLOAD PRIORITY 5 AUTO MERGE;


-- A317FA664ABA425DB50CA4CF071C7AFC.CAT_SOLICITANTES definition

CREATE COLUMN TABLE "A317FA664ABA425DB50CA4CF071C7AFC"."CAT_SOLICITANTES" ("ID" NVARCHAR(36) DEFAULT SYSUUID,
"NOMBRE" NVARCHAR(150) NOT NULL ,
"ACTIVO" TINYINT DEFAULT 1,
"CREADO_EN" LONGDATE DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY ("ID")) UNLOAD PRIORITY 5 AUTO MERGE;


-- A317FA664ABA425DB50CA4CF071C7AFC.ACTIVIDADES definition

CREATE COLUMN TABLE "A317FA664ABA425DB50CA4CF071C7AFC"."ACTIVIDADES" ("ID" NVARCHAR(36) NOT NULL ,
"ID_PROYECTO" NVARCHAR(36) NOT NULL ,
"NOMBRE_ACTIVIDAD" NVARCHAR(255) NOT NULL ,
"FRIENDLY_NAME" NVARCHAR(1000),
"DESCRIPCION" NVARCHAR(1000),
"FECHA_SOLICITUD" DATE,
"SOLICITANTE" NVARCHAR(150),
"TIPO" NVARCHAR(30),
"FECHA_INICIO" DATE,
"DIAS_ACORDADOS" SMALLINT,
"FECHA_FIN_EST" DATE,
"FECHA_FIN_REAL" DATE,
"ID_ESTATUS" NVARCHAR(36) NOT NULL ,
"AVANCE_PCT" TINYINT DEFAULT 0,
"PRIORIDAD" TINYINT DEFAULT 2,
"ASIGNADO_A" NVARCHAR(36),
"CREADO_EN" LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL ,
"ACTUALIZADO_EN" LONGDATE,
"CREADO_POR" NVARCHAR(36),
"ACTUALIZADO_POR" NVARCHAR(36),
"ID_ACTIVIDAD_PADRE" NVARCHAR(36),
PRIMARY KEY ("ID")) UNLOAD PRIORITY 5 AUTO MERGE ;

ALTER TABLE "A317FA664ABA425DB50CA4CF071C7AFC"."ACTIVIDADES" ADD FOREIGN KEY ("ID_PROYECTO") REFERENCES "A317FA664ABA425DB50CA4CF071C7AFC"."PROYECTOS" ("ID") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;

ALTER TABLE "A317FA664ABA425DB50CA4CF071C7AFC"."ACTIVIDADES" ADD FOREIGN KEY ("ID_ESTATUS") REFERENCES "A317FA664ABA425DB50CA4CF071C7AFC"."CAT_ESTATUS_ACTIVIDAD" ("ID") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;

ALTER TABLE "A317FA664ABA425DB50CA4CF071C7AFC"."ACTIVIDADES" ADD FOREIGN KEY ("ASIGNADO_A") REFERENCES "A317FA664ABA425DB50CA4CF071C7AFC"."USUARIOS" ("ID") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;



-- A317FA664ABA425DB50CA4CF071C7AFC.ACTIVIDAD_RESPONSABLES definition

CREATE COLUMN TABLE "A317FA664ABA425DB50CA4CF071C7AFC"."ACTIVIDAD_RESPONSABLES" ("ID_ACTIVIDAD" NVARCHAR(36) NOT NULL ,
"ID_USUARIO" NVARCHAR(36) NOT NULL ,
"CREADO_EN" LONGDATE DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY INVERTED INDIVIDUAL("ID_ACTIVIDAD", "ID_USUARIO")) UNLOAD PRIORITY 5 AUTO MERGE ;

ALTER TABLE "A317FA664ABA425DB50CA4CF071C7AFC"."ACTIVIDAD_RESPONSABLES" ADD FOREIGN KEY ("ID_ACTIVIDAD") REFERENCES "A317FA664ABA425DB50CA4CF071C7AFC"."ACTIVIDADES" ("ID") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;

ALTER TABLE "A317FA664ABA425DB50CA4CF071C7AFC"."ACTIVIDAD_RESPONSABLES" ADD FOREIGN KEY ("ID_USUARIO") REFERENCES "A317FA664ABA425DB50CA4CF071C7AFC"."USUARIOS" ("ID") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;



-- A317FA664ABA425DB50CA4CF071C7AFC.ACTIVIDAD_RECURSOS definition

CREATE COLUMN TABLE "A317FA664ABA425DB50CA4CF071C7AFC"."ACTIVIDAD_RECURSOS" ("ID_ACTIVIDAD" NVARCHAR(36) NOT NULL ,
"ID_RECURSO" NVARCHAR(36) NOT NULL ,
"CREADO_EN" LONGDATE DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY INVERTED INDIVIDUAL("ID_ACTIVIDAD", "ID_RECURSO")) UNLOAD PRIORITY 5 AUTO MERGE ;

ALTER TABLE "A317FA664ABA425DB50CA4CF071C7AFC"."ACTIVIDAD_RECURSOS" ADD FOREIGN KEY ("ID_ACTIVIDAD") REFERENCES "A317FA664ABA425DB50CA4CF071C7AFC"."ACTIVIDADES" ("ID") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;

ALTER TABLE "A317FA664ABA425DB50CA4CF071C7AFC"."ACTIVIDAD_RECURSOS" ADD FOREIGN KEY ("ID_RECURSO") REFERENCES "A317FA664ABA425DB50CA4CF071C7AFC"."CAT_RECURSOS" ("ID") ON
UPDATE
    RESTRICT ON
    DELETE
    RESTRICT ENFORCED VALIDATED INITIALLY IMMEDIATE;


-- //////////////////////////////////////////////////////

-- ============================================================
-- MÓDULO CALENDARIO / AUSENCIAS
-- Ejecutar en SAP HANA Cloud antes de iniciar la aplicación
-- ============================================================

-- 1. Tabla principal de ausencias por usuario
CREATE COLUMN TABLE "AUSENCIAS_USUARIO" (
    "ID"            NVARCHAR(36)  NOT NULL DEFAULT SYSUUID,
    "ID_USUARIO"    NVARCHAR(36)  NOT NULL,
    "FECHA_INICIO"  DATE          NOT NULL,
    "FECHA_FIN"     DATE          NOT NULL,
    "TIPO"          NVARCHAR(50)  NOT NULL,  -- VACACIONES | INCAPACIDAD | DIA_LIBRE | PERMISO | OTRO
    "HORAS_DIA"     DECIMAL(4,2)  DEFAULT 8 NOT NULL,  -- horas ausentes por día (8 = día completo)
    "DESCRIPCION"   NVARCHAR(500),
    "CREADO_EN"     LONGDATE      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "CREADO_POR"    NVARCHAR(36),
    "ACTUALIZADO_EN" LONGDATE,
    PRIMARY KEY ("ID")
) UNLOAD PRIORITY 5 AUTO MERGE;

ALTER TABLE "AUSENCIAS_USUARIO"
    ADD FOREIGN KEY ("ID_USUARIO")
    REFERENCES "USUARIOS" ("ID")
    ON UPDATE RESTRICT ON DELETE RESTRICT
    ENFORCED VALIDATED INITIALLY IMMEDIATE;


-- 2. Tabla de días festivos (editables por el equipo)
CREATE COLUMN TABLE "DIAS_FESTIVOS" (
    "ID"            NVARCHAR(36)  NOT NULL DEFAULT SYSUUID,
    "FECHA"         DATE          NOT NULL,
    "NOMBRE"        NVARCHAR(150) NOT NULL,
    "TIPO"          NVARCHAR(50)  DEFAULT 'OFICIAL',   -- OFICIAL | PUENTE | ESPECIAL
    "APLICA_TODOS"  TINYINT       DEFAULT 1,           -- 1 = aplica a todo el equipo
    "ACTIVO"        TINYINT       DEFAULT 1,
    "CREADO_EN"     LONGDATE      DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("ID")
) UNLOAD PRIORITY 5 AUTO MERGE;


-- 3. Días festivos México 2025 precargados
INSERT INTO "DIAS_FESTIVOS" ("FECHA","NOMBRE","TIPO") VALUES ('2025-01-01', 'Año Nuevo', 'OFICIAL');
INSERT INTO "DIAS_FESTIVOS" ("FECHA","NOMBRE","TIPO") VALUES ('2025-02-03', 'Día de la Constitución (puente)', 'PUENTE');
INSERT INTO "DIAS_FESTIVOS" ("FECHA","NOMBRE","TIPO") VALUES ('2025-03-17', 'Natalicio de Benito Juárez (puente)', 'PUENTE');
INSERT INTO "DIAS_FESTIVOS" ("FECHA","NOMBRE","TIPO") VALUES ('2025-04-17', 'Jueves Santo', 'ESPECIAL');
INSERT INTO "DIAS_FESTIVOS" ("FECHA","NOMBRE","TIPO") VALUES ('2025-04-18', 'Viernes Santo', 'OFICIAL');
INSERT INTO "DIAS_FESTIVOS" ("FECHA","NOMBRE","TIPO") VALUES ('2025-05-01', 'Día del Trabajo', 'OFICIAL');
INSERT INTO "DIAS_FESTIVOS" ("FECHA","NOMBRE","TIPO") VALUES ('2025-09-16', 'Día de la Independencia', 'OFICIAL');
INSERT INTO "DIAS_FESTIVOS" ("FECHA","NOMBRE","TIPO") VALUES ('2025-11-17', 'Día de la Revolución (puente)', 'PUENTE');
INSERT INTO "DIAS_FESTIVOS" ("FECHA","NOMBRE","TIPO") VALUES ('2025-12-25', 'Navidad', 'OFICIAL');

-- 4. Días festivos México 2026
INSERT INTO "DIAS_FESTIVOS" ("FECHA","NOMBRE","TIPO") VALUES ('2026-01-01', 'Año Nuevo', 'OFICIAL');
INSERT INTO "DIAS_FESTIVOS" ("FECHA","NOMBRE","TIPO") VALUES ('2026-02-02', 'Día de la Constitución (puente)', 'PUENTE');
INSERT INTO "DIAS_FESTIVOS" ("FECHA","NOMBRE","TIPO") VALUES ('2026-03-16', 'Natalicio de Benito Juárez (puente)', 'PUENTE');
INSERT INTO "DIAS_FESTIVOS" ("FECHA","NOMBRE","TIPO") VALUES ('2026-04-02', 'Jueves Santo', 'ESPECIAL');
INSERT INTO "DIAS_FESTIVOS" ("FECHA","NOMBRE","TIPO") VALUES ('2026-04-03', 'Viernes Santo', 'OFICIAL');
INSERT INTO "DIAS_FESTIVOS" ("FECHA","NOMBRE","TIPO") VALUES ('2026-05-01', 'Día del Trabajo', 'OFICIAL');
INSERT INTO "DIAS_FESTIVOS" ("FECHA","NOMBRE","TIPO") VALUES ('2026-09-16', 'Día de la Independencia', 'OFICIAL');
INSERT INTO "DIAS_FESTIVOS" ("FECHA","NOMBRE","TIPO") VALUES ('2026-11-16', 'Día de la Revolución (puente)', 'PUENTE');
INSERT INTO "DIAS_FESTIVOS" ("FECHA","NOMBRE","TIPO") VALUES ('2026-12-25', 'Navidad', 'OFICIAL');


-- ///////////////////////////////////////////////////////

-- Setup incremental para Plan de trabajo
-- Ejecutar en el schema de la aplicación.
-- Si una sentencia falla por columna existente/no existente, revísala según tu estado actual.

ALTER TABLE "ACTIVIDADES" ADD ("FRIENDLY_NAME" NVARCHAR(1000));
UPDATE "ACTIVIDADES"
SET "FRIENDLY_NAME" = COALESCE("FRIENDLY_NAME", "PLAN_TRABAJO")
WHERE COALESCE("PLAN_TRABAJO", '') <> '';

ALTER TABLE "ACTIVIDADES" DROP ("PLAN_TRABAJO");
ALTER TABLE "ACTIVIDADES" DROP ("NOMBRE_TECNICO");

ALTER TABLE "ACTIVIDADES" ADD ("DIAS_ACORDADOS" SMALLINT);
ALTER TABLE "ACTIVIDADES" ADD ("FECHA_FIN_EST" DATE);
ALTER TABLE "ACTIVIDADES" ADD ("TIPO" NVARCHAR(30));

CREATE OR REPLACE VIEW "VW_plan_de_trabajo" AS
SELECT
    A."ID",
    A."NOMBRE_ACTIVIDAD",
    A."FRIENDLY_NAME",
    A."ID_PROYECTO",
    P."NOMBRE_PROYECTO",
    A."ID_ESTATUS",
    E."DESCRIPCION" AS "ESTATUS",
    E."COLOR_HEX" AS "ESTATUS_COLOR",
    A."FECHA_INICIO",
    A."FECHA_FIN_EST",
    A."FECHA_FIN_REAL",
    A."DIAS_ACORDADOS",
    A."AVANCE_PCT",
    A."PRIORIDAD",
    A."CREADO_EN",
    CASE
        WHEN A."DIAS_ACORDADOS" IS NOT NULL
             AND A."FECHA_INICIO" IS NOT NULL
             AND DAYS_BETWEEN(A."FECHA_INICIO", CURRENT_DATE) > A."DIAS_ACORDADOS"
             AND UPPER(E."DESCRIPCION") NOT IN ('COMPLETADO', 'CANCELADO', 'ESPERANDO APROBACIÓN')
        THEN 1
        ELSE 0
    END AS "EN_RETRASO",
    COALESCE((
        SELECT STRING_AGG(U2."NOMBRE_COMPLETO", ', ')
        FROM "ACTIVIDAD_RESPONSABLES" AR
        JOIN "USUARIOS" U2 ON AR."ID_USUARIO" = U2."ID"
        WHERE AR."ID_ACTIVIDAD" = A."ID"
    ), 'Sin asignar') AS "RESPONSABLES"
FROM "ACTIVIDADES" A
JOIN "PROYECTOS" P ON A."ID_PROYECTO" = P."ID"
JOIN "CAT_ESTATUS_ACTIVIDAD" E ON A."ID_ESTATUS" = E."ID"
WHERE A."ID_ACTIVIDAD_PADRE" IS NULL
    AND UPPER(COALESCE(A."NOMBRE_ACTIVIDAD", '')) NOT LIKE '⚡ %'
WITH READ ONLY;


CREATE COLUMN TABLE "CAT_ENTREGABLES" (
    "ID" NVARCHAR(32) NOT NULL,
    "NOMBRE" NVARCHAR(255) NOT NULL,
    "ACTIVO" TINYINT DEFAULT 1 NOT NULL, -- 1 = Activo, 0 = Inactivo
    "FECHA_CREACION" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY ("ID")
);

INSERT INTO "CAT_ENTREGABLES" ("ID", "NOMBRE", "ACTIVO") VALUES (SYSUUID, '1 Desarrollo', 1);

